import numpy as np
import matplotlib.pyplot as plt

show = False # Turn it to True if you want to plot input data in a image
# Input data --------------------------------------------
i_matrix = np.array([[0, 1, 0, 0], [0, 0, 1, 0]])
print('Original matrix: \n', i_matrix)
if show:
    plt.matshow(i_matrix)
    plt.title('Original matrix')
    plt.show()

# Function ----------------------------------------------
def split(matrix, depth):
    '''
    matrix: matrix shape(mxn)
    Depth: a number > 1
    '''
    n_tensor = [] # new created tensor
    for i in range(0, depth):
        # Creating the padding zero to compensate for the lost path of the shifted matrix
        r_matrix = len(matrix)
        pad = np.zeros((r_matrix, i))

        # 1: a new matrix is generated by concatenate the cut matrix and zero padding
        # 2: Collecting new matrices into a tensor
        n_tensor.append(np.concatenate((matrix[:, i:], pad), axis=1))
    return np.array(n_tensor)

# Show each lice of tensor after using split() function
print('\n' + '#'*15 + ' Print each slice of tensor after using split function ' + '#'*10)
tensor = split(i_matrix, 4)
for idx, i in enumerate(tensor):
    print(f'\nDepth number {idx+1}:')
    print(i)